-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN', 'OWNER');

-- CreateEnum
CREATE TYPE "ChatType" AS ENUM ('private', 'group', 'supergroup', 'channel');

-- CreateTable
CREATE TABLE "chats" (
    "chat_id" INT8 NOT NULL,
    "chat_type" "ChatType" NOT NULL,
    "language_code" STRING,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "role" "Role" NOT NULL DEFAULT 'USER'
);

-- CreateTable
CREATE TABLE "bots" (
    "bot_id" INT8 NOT NULL,
    "token" STRING NOT NULL,
    "username" STRING NOT NULL,
    "first_name" STRING NOT NULL DEFAULT 'bot_name',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL
);

-- CreateTable
CREATE TABLE "posts" (
    "postId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "chat_id" INT8 NOT NULL,
    "bot_id" INT8 NOT NULL,
    "text" STRING,
    "entities" JSONB,
    "reply_markup" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateIndex
CREATE UNIQUE INDEX "chats_chat_id_key" ON "chats"("chat_id");

-- CreateIndex
CREATE UNIQUE INDEX "bots_bot_id_key" ON "bots"("bot_id");

-- CreateIndex
CREATE UNIQUE INDEX "bots_token_key" ON "bots"("token");

-- CreateIndex
CREATE UNIQUE INDEX "posts_postId_key" ON "posts"("postId");

-- AddForeignKey
ALTER TABLE "posts" ADD CONSTRAINT "posts_chat_id_fkey" FOREIGN KEY ("chat_id") REFERENCES "chats"("chat_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "posts" ADD CONSTRAINT "posts_bot_id_fkey" FOREIGN KEY ("bot_id") REFERENCES "bots"("bot_id") ON DELETE RESTRICT ON UPDATE CASCADE;
